### ISSUE TITLE
Command output?

### ISSUE THREAD

**Issue by brettz9** [ksxatompackages/cmd-exec#15]
I'm in Windows using your "console:cmd" but when I run commands (e.g., `npm help` to test), I see a console window open and then close and no output is shown in the console pane within Atom. Am I doing something wrong? Thanks!

**Comment by KSXGitHub** [comment]
You need to set property `"attached"` to `true`, e.g.

``` cson

          "console:cmd":
            type: "spawn"
            path: "cmd"
            console: true
            attached: true # HERE
            hideInputText: true # you wouldn't want to see your cmd commands display twice
            utils: ["clear", "cls", "ClearScreen"] # just clear screen
            closeOnExit: true
```

**Comment by brettz9** [comment]
Very nice, thanks! Btw, you might want to document this in your documentation (and/or specs), as it is the only feature I think that is not mentioned there.

I'm really enjoying your add-on, btw, especially in conjunction with [command-toolbar](https://atom.io/packages/command-toolbar)...

**Comment by KSXGitHub** [comment]
I already do it, thanks!
