### ISSUE TITLE
Dialog to accept arguments to pass on to command

### ISSUE THREAD

**Issue by brettz9** [ksxatompackages/cmd-exec#16]
It would be awfully handy if cmd-exec commands could add a property to prompt the user for a dialog of arguments (ideally in separate textboxes depending on the number asked for, with a customizable dialog title or questions) which could then be used as a variable within the command path.

I'd like to use it, for example, to use `npm run ....` against the current file's `package.json` and not all of the possibilities are predefined nor would I want to add each one within `config.cson`.

I'm using your project in combination with [command-toolbar](https://atom.io/packages/command-toolbar), so my ideal scenario would be to click a "npm run" button in the toolbar (which is linked to my cmd-exec command), get a dialog asking me for which script to run, and then hit ok to run it.

Thanks!

**Comment by KSXGitHub** [comment]
This feature wouldn't be added here, I'll statify you in another package soon! :smile:
