### ISSUE TITLE
set config values dynamically

### ISSUE THREAD

**Issue by h-a-n-n-e-s** [ksxatompackages/cmd-exec#17]
In config.cson, I want to set the value of 'wdir' dynamically from my init script.
The config.cson looks something like this
`"cmd-exec":
    commands: [
      {
        target: "atom-text-editor"
        data:
          "cmd-exec:command1":
            type: "spawn"
            path: "command1"
          "cmd-exec:command2":
            type: "spawn"
            path: "command2"
            wdir: {}
      }
    ]`

What's the right syntax to do this?
The problem is the array structure [{}]
If I do some variants of this
`atom.config.set('cmd-exec.commands.???.wdir', my_wdir )`
in my init script, I only get errors.

**Comment by KSXGitHub** [comment]
`cmd-exec.commands` is an array, so you need `cmd-exec.commands[index]["cmd-exec:command1"].wdir`.

P.S. It seems too complicate, so I plan to create an alternate that is accessible from init script as well as atom packages

**Comment by h-a-n-n-e-s** [comment]
`atom.config.set('cmd-exec.commands[index]["cmd-exec:command1"].wdir', my_wdir )`
still doesn't seem to work for me.
Yes, you're right, this array structure in the config is not very straight forward. Maybe there's a simpler way.

Two other things: I wasn't able to set the style of the console output (font size for example) in my style file. What's the best way to do this? Further, how can I stop the process running in a console with a short-key?

**Comment by KSXGitHub** [comment]
1. Oh, I was missing something - `.data`, you need `cmd-exec.commands[index].data["cmd-exec:command1"].wdir`. See [example config.cson](https://github.com/ksxatompackages/cmd-exec-documentation/blob/master/examples/config.cson#L12).
2. The console output uses `.text-success.stdout` css class for normal output (from stdout) and `.text-error.stderr` for error output (from stderr). Anyway, I'll try styling the console output to know what made the issue.
3. Any running process would be terminated if you the pane-item (close tab that contains the console). You just need to find which command closes pane-items (Press <kbd>Ctrl+Shift+P</kbd> to find it) and assign a keybinding.

**Comment by h-a-n-n-e-s** [comment]
1. Nope, still doesn't work. But never mind, I changed something else so I don't need to set 'wdir' anymore. You should better get rid of these array structures in general, it's bad style.
2. `.text-success` is the output outside of the console, like the "Process finished,..." for example. I finally figured out that `.from-data` is what controls output inside the console.
   Further, I now know why style changes never worked for your package, because you use the `!important` tag after many style settings, which does not allow others to change these. You should better get rid of these tags.
   Finally, I found the correct path to the console style, which is
   `.cmd-exec.view-console #readablediv #innerreadablediv #outputpre`
   but maybe this is not necessary anymore, once you get rid of `!important`, then `.cmd-exec.view-console` should be enough to set some styles in that scope.

New point:
4. When a command is running, what is that entry field at the bottom of the pane with the "Enter" written left to it? How can I make it not appear?

**Comment by KSXGitHub** [comment]
1. I won't, instead, I will create an alternate package and deprecate this one, soon (I told you, didn't I?).
2. Yes, I used `!important` for some css attributes, I can remove it, but I'm in a long holiday right now, so I will do it later or can you fork this one, change it, and create a pull request.
3. (extended) I found that `tabs:close-tab` closes tabs and so you can terminate running process in console. However, if you want to terminate subprocesses (e.g. you use cmd-exec to spawn bash/cmd to enter some commands), that is impossible with Node.js + Electron alone.
4. That "enter" just like <kbd>enter</kbd> in your keyboard. Have you ever spawn a process that read data from stdin (e.g. bash/cmd)? May be your commands don't use stdin to communicate with you but I don't know how to determine which process don't use stdin, so a mini atom-text-editor and that enter button would be shown as long as process is running. I will add an option to hide the atom-text-editor and the button

**Comment by h-a-n-n-e-s** [comment]
1. Great! Your package is already pretty good! So you only need to take care of a few things.
2. Messing around in other people's packages is not my thing. I'll rather write my own now, with some inspiration from yours. Enjoy your holiday!
3. If the process is a shell script which starts other programs (like in my case), those won't be canceled by closing the tab. But I took care of this.
4. I use the shell more like a console output from scripts, so I don't need user input via stdin.

Thanks for all your help!
